/* eslint-disable react/no-unescaped-entities */
"use client"
import Link from "next/link"
import TopNavbar from "@/components/TopNavbar"

export default function PrivacyPolicy() {
	return (

		<div className="container mx-auto px-4 py-16 max-w-4xl">
			{/* Navbar */}
			<TopNavbar isTransparent />
			<h1 className="text-4xl font-bold mb-8 mt-8">Privacy Policy</h1>

			<section className="mb-8">
				<h2 className="text-2xl font-semibold mb-4">1. Introduction</h2>
				<p className="mb-4">
					This Privacy Policy explains how <span className="font-galano">Altwy</span> ("we", "us", or "our") uses cookies and similar technologies on our website. We use cookies solely for Google Analytics to help us understand how visitors use our site.
				</p>
			</section>

			<section className="mb-8">
				<h2 className="text-2xl font-semibold mb-4">2. What are Cookies?</h2>
				<p className="mb-4">
					Cookies are small text files that are placed on your device when you visit a website. They are widely used to make websites work more efficiently and provide information to the owners of the site.
				</p>
			</section>

			<section className="mb-8">
				<h2 className="text-2xl font-semibold mb-4">3. How We Use Cookies</h2>
				<p className="mb-4">
					We use Google Analytics, a web analytics service provided by Google, Inc. Google Analytics uses cookies to help us analyze how users use our site. The information generated by the cookie about your use of our website (including your IP address) will be transmitted to and stored by Google on servers in the United States.
				</p>
				<p className="mb-4">
					Google will use this information for the purpose of evaluating your use of our website, compiling reports on website activity for us and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf.
				</p>
			</section>

			<section className="mb-8">
				<h2 className="text-2xl font-semibold mb-4">4. Managing Cookies</h2>
				<p className="mb-4">
					You can control and/or delete cookies as you wish. You can delete all cookies that are already on your computer and you can set most browsers to prevent them from being placed. If you do this, however, you may have to manually adjust some preferences every time you visit a site and some services and functionalities may not work.
				</p>
				<p className="mb-4">
					To opt out of being tracked by Google Analytics across all websites, visit <a href="http://tools.google.com/dlpage/gaoptout" className="text-[#00FF88] hover:underline">http://tools.google.com/dlpage/gaoptout</a>.
				</p>
			</section>

			<section className="mb-8">
				<h2 className="text-2xl font-semibold mb-4">5. Changes to This Policy</h2>
				<p className="mb-4">
					We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.
				</p>
			</section>

			<section className="mb-8">
				<h2 className="text-2xl font-semibold mb-4">6. Contact Us</h2>
				<p className="mb-4">
					If you have any questions about this Privacy Policy, please <Link href="/contact" className="text-[#00FF88] hover:underline">contact us here.</Link>
				</p>
			</section>
		</div>
	)
}

